using cxx

hxx{*}: extension =
cxx{*}: extension = cpp
ixx{*}: extension = ipp

cxx.poptions += "-I$out_root"

using cli

exe{driver}: cxx{driver} cxx{test}
cxx{test} hxx{test}: cli{test}

#exe{driver}: cxx{driver} cli.cxx{test}
#cli.cxx{test}: cli{test}
