#define           # expected name
#define foo       # expected :
#define foo:      # expected name
#define foo: bar  # unknown target type

define foo: file
foo{FOO}:         # verify name is foo{FOO} and not file{FOO} with --verbose 6 

#define foo: dir  # already define in this scope

define bar: foo
bar{BAR}:         # verify name is bar{BAR} with --verbose 6

./:
