# file      : tests/test/script/integration/buildfile
# copyright : Copyright (c) 2014-2016 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

./: test{testscript}

test{*}: test = $build.driver
