# file      : tests/test/script/integration/buildfile
# copyright : Copyright (c) 2014-2019 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

# Test integration of testscript into build system.
#

./: testscript $b
