# file      : tests/depdb/buildfile
# copyright : Copyright (c) 2014-2016 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs = libbutl%lib{butl}

exe{driver}: cxx{driver ../../build2/{depdb}} $libs
exe{driver}: test.arguments = $out_base/test.d
