# file      : tests/test/script/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

d = builtin/ runner/
./: $d file{common.test}
include $d
