# file      : tests/test/script/buildfile
# copyright : Copyright (c) 2014-2016 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

d = builtin/ integration/ runner/
./: $d
include $d
