// -*- C++ -*-
//
// This file was generated by CLI, a command line interface
// compiler for C++.
//

#ifndef BX_BX_OPTIONS_HXX
#define BX_BX_OPTIONS_HXX

// Begin prologue.
//
//
// End prologue.

#include <libbuild2/common-options.hxx>

namespace build2
{
  class bx_options
  {
    public:
    bx_options ();

    // Return true if anything has been parsed.
    //
    bool
    parse (int& argc,
           char** argv,
           bool erase = false,
           ::build2::build::cli::unknown_mode option = ::build2::build::cli::unknown_mode::fail,
           ::build2::build::cli::unknown_mode argument = ::build2::build::cli::unknown_mode::stop);

    bool
    parse (int start,
           int& argc,
           char** argv,
           bool erase = false,
           ::build2::build::cli::unknown_mode option = ::build2::build::cli::unknown_mode::fail,
           ::build2::build::cli::unknown_mode argument = ::build2::build::cli::unknown_mode::stop);

    bool
    parse (int& argc,
           char** argv,
           int& end,
           bool erase = false,
           ::build2::build::cli::unknown_mode option = ::build2::build::cli::unknown_mode::fail,
           ::build2::build::cli::unknown_mode argument = ::build2::build::cli::unknown_mode::stop);

    bool
    parse (int start,
           int& argc,
           char** argv,
           int& end,
           bool erase = false,
           ::build2::build::cli::unknown_mode option = ::build2::build::cli::unknown_mode::fail,
           ::build2::build::cli::unknown_mode argument = ::build2::build::cli::unknown_mode::stop);

    bool
    parse (::build2::build::cli::scanner&,
           ::build2::build::cli::unknown_mode option = ::build2::build::cli::unknown_mode::fail,
           ::build2::build::cli::unknown_mode argument = ::build2::build::cli::unknown_mode::stop);

    // Merge options from the specified instance appending/overriding
    // them as if they appeared after options in this instance.
    //
    void
    merge (const bx_options&);

    // Option accessors.
    //
    const uint64_t&
    build2_metadata () const;

    bool
    build2_metadata_specified () const;

    const bool&
    v () const;

    const bool&
    V () const;

    const bool&
    quiet () const;

    const uint16_t&
    verbose () const;

    bool
    verbose_specified () const;

    const bool&
    diag_color () const;

    const bool&
    no_diag_color () const;

    const size_t&
    max_stack () const;

    bool
    max_stack_specified () const;

    const string&
    pager () const;

    bool
    pager_specified () const;

    const strings&
    pager_option () const;

    bool
    pager_option_specified () const;

    const string&
    options_file () const;

    bool
    options_file_specified () const;

    const dir_path&
    default_options () const;

    bool
    default_options_specified () const;

    const bool&
    no_default_options () const;

    const bool&
    help () const;

    const bool&
    version () const;

    // Print usage information.
    //
    static ::build2::build::cli::usage_para
    print_usage (::std::ostream&,
                 ::build2::build::cli::usage_para = ::build2::build::cli::usage_para::none);

    // Implementation details.
    //
    protected:
    bool
    _parse (const char*, ::build2::build::cli::scanner&);

    private:
    bool
    _parse (::build2::build::cli::scanner&,
            ::build2::build::cli::unknown_mode option,
            ::build2::build::cli::unknown_mode argument);

    public:
    uint64_t build2_metadata_;
    bool build2_metadata_specified_;
    bool v_;
    bool V_;
    bool quiet_;
    uint16_t verbose_;
    bool verbose_specified_;
    bool diag_color_;
    bool no_diag_color_;
    size_t max_stack_;
    bool max_stack_specified_;
    string pager_;
    bool pager_specified_;
    strings pager_option_;
    bool pager_option_specified_;
    string options_file_;
    bool options_file_specified_;
    dir_path default_options_;
    bool default_options_specified_;
    bool no_default_options_;
    bool help_;
    bool version_;
  };
}

// Print page usage information.
//
namespace build2
{
  ::build2::build::cli::usage_para
  print_bx_usage (::std::ostream&,
                  ::build2::build::cli::usage_para = ::build2::build::cli::usage_para::none);
}

#include <bx/bx-options.ixx>

// Begin epilogue.
//
//
// End epilogue.

#endif // BX_BX_OPTIONS_HXX
