# file      : libbuild2/cc/buildfile
# copyright : Copyright (c) 2014-2019 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

include ../
imp_libs = ../lib{build2} # Implied interface dependency.

import imp_libs += libpkgconf%lib{pkgconf}

include ../bin/
int_libs = ../bin/lib{build2-bin}

./: lib{build2-cc}: libul{build2-cc}: {hxx ixx txx cxx}{** -**.test...} \
  $int_libs $imp_libs

# Unit tests.
#
exe{*.test}:
{
  test = true
  install = false
}

for t: cxx{**.test...}
{
  d = $directory($t)
  n = $name($t)...
  b = $path.base($name($t))

  ./: $d/exe{$n}: $t $d/{hxx ixx txx}{+$n} $d/testscript{+$n +$b+*.test...}
  $d/exe{$n}: libul{build2-cc}: bin.whole = false
}

# Build options.
#
obja{*}: cxx.poptions += -DLIBBUILD2_CC_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBBUILD2_CC_SHARED_BUILD

# Export options.
#
lib{build2-cc}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $int_libs
}

liba{build2-cc}: cxx.export.poptions += -DLIBBUILD2_CC_STATIC
libs{build2-cc}: cxx.export.poptions += -DLIBBUILD2_CC_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
# And because this is a build system module, we also embed the same value as
# the interface version (note that we cannot use build.version.interface for
# bundled modules because we could be built with a different version of the
# build system).
#
ver = ($version.pre_release    \
       ? "$version.project_id" \
       : "$version.major.$version.minor")

lib{build2-cc}: bin.lib.version = @"-$ver"
libs{build2-cc}: bin.lib.load_suffix = "-$ver"

# Install into the libbuild2/cc/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libbuild2/cc/
  install.subdirs = true
}
