print "foo   bar"
print "foo
bar"

foo = "fo o"
bar = " bar "

print "$foo"
print "$bar"
print "$foo $bar"
print "$foo$bar"

print "[ $foo ]"
print "[ $bar ]"
print "[ $foo $bar ]"
print "[ $foo/$bar ]"

print $foo'bar'
print $foo"$bar"
print "$foo"bar

# Quoting and evaluation context.
#
print ("x{foo bar}")
#print "(x{foo bar})" # multiple values in concatenating context expansion
print "({foo})"
print "('foo bar')"
print "("foo bar")"
print "("$foo bar")"
print "("$foo ($bar)")"

# Quoting and escaping/multiline.
#
print \
"foo"\
"bar"

print \
"foo\
bar"

print \
'foo\
bar'

print \
"foo (fox  \
)
bar"

./:
