# file      : unit-tests/test/script/regex/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

#@@ Temporary until we get utility library support.
#
import libs = libbutl%lib{butl}
src = test/script/regex

exe{driver}: cxx{driver} ../../../../build2/cxx{$src} ../../../../build2/liba{b} $libs

include ../../../../build2/
