# file      : tests/buildfile
# copyright : Copyright (c) 2014-2016 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

d = directive/ expansion/ function/ test/ value/
./: $d file{common.test}
include $d
