if ($p_a == as)
{
  v = x
}
elif ($p_a == ap)
{
  v += s
}
elif ($p_a == pr)
{
  v =+ p
}

print "p     :" $v

d/:
{
  if ($p_d_a == as)
  {
    v = x
  }
  elif ($p_d_a == ap)
  {
    v += s
  }
  elif ($p_d_a == pr)
  {
    v =+ p
  }

  print "p/d   :" $v

  if ($p_d_t_a == as)
  {
    file{t}: v = x
  }
  elif ($p_d_t_a == ap)
  {
    file{t}: v += s
  }
  elif ($p_d_t_a == pr)
  {
    file{t}: v =+ p
  }

  print "p/d/t :" $(file{t}: v)
}

./:
