# file      : tests/cc/preprocessed/buildfile
# copyright : Copyright (c) 2014-2018 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

# Test {c, cxx}.preprocessed logic.
#

./: testscript $b
