# file      : tests/test/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

./: config-test/ script/ script-integration/ \
file{common.test}

