# file      : tests/test/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

d = config-test/ script/ script-integration/
./: $d file{common.test}
include $d
