# file      : tests/cc/modules/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

# Test C++ modules support.
#

./: test{testscript} $b
