# file      : unit-tests/function/buildfile
# copyright : Copyright (c) 2014-2016 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

#@@ Temporary until we get utility library support.
#
import libs = libbutl%lib{butl}
src = token lexer diagnostics utility variable name b-options types-parsers \
context scope parser target operation rule prerequisite file module function \
functions-path algorithm search dump filesystem config/{utility init operation}

exe{driver}: cxx{driver} ../../build2/cxx{$src} $libs test{call syntax}

include ../../build2/
