# Out of amalgamation.
#
../../:
{
  print -1: $project
  print -1: $src_base
  print -1: $out_base
}

# In amalgamation.
#
../s/:
{
  print 0: $project
  print 0: $src_base
  print 0: $out_base
}

# In project.
#
s/:
{
  print 1: $project
  print 1: $src_base
  print 1: $out_base
}

# In sub-project.
#
l2/s/:
{
  print 2: $project
  print 2: $src_base
  print 2: $out_base
}

./:
