# file      : unit-tests/scheduler/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

#@@ Temporary until we get utility library support.
#
import libs = libbutl%lib{butl}
src = token lexer diagnostics utility variable name b-options types-parsers \
context scope parser target operation rule prerequisite file module function \
functions-builtin functions-path functions-process-path functions-string \
functions-target-triplet algorithm search dump filesystem scheduler \
config/{utility init operation} spec

exe{driver}: cxx{driver} ../../build2/cxx{$src} ../../build2/liba{b} $libs

include ../../build2/
