# file      : unit-tests/scheduler/buildfile
# copyright : Copyright (c) 2014-2018 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

include ../../build2/
exe{driver}: {hxx cxx}{*} ../../build2/libu{b}
