# file      : unit-tests/cc/parser/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

include ../../../build2/
exe{driver}: {hxx cxx}{*} ../../../build2/libu{b} test{*}
