if ($p.t != [null])
{
  [$p.t] p.v = [null]
}

print "/     :" $(/: p.v)

if ($p.a == as)
{
  p.v = x
}
elif ($p.a == ap)
{
  p.v += s
}
elif ($p.a == pr)
{
  p.v =+ p
}

print ".     :" $p.v

d/
{
  if ($p.d_a == as)
  {
    p.v = x
  }
  elif ($p.d_a == ap)
  {
    p.v += s
  }
  elif ($p.d_a == pr)
  {
    p.v =+ p
  }

  print "d     :" $p.v


  if ($p.d_t_a == as)
  {
    file{t}: p.v = x
  }
  elif ($p.d_t_a == ap)
  {
    file{t}: p.v += s
  }
  elif ($p.d_t_a == pr)
  {
    file{t}: p.v =+ p
  }

  print "d/t   :" $(file{t}: p.v)
}

include p/
./:
