# file      : tests/test/script/builtin/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

./: test{cat cp echo mkdir rm rmdir sed test touch} $b
