# file      : tests/lexer/buildfile
# copyright : Copyright (c) 2014-2015 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

exe{driver}: cxx{driver ../../../build/{lexer diagnostics utility}}
