# file      : unit-tests/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

d = function/ lexer/ scheduler/ test/script/
./: $d
include $d
