# file      : tests/test/script/runner/buildfile
# copyright : Copyright (c) 2014-2018 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

./: testscript{*} exe{driver} $b

testscript{*}: target = exe{driver}

import libs = libbutl%lib{butl}
exe{driver}: {hxx cxx}{*} $libs
