# file      : tests/test/script/runner/buildfile
# copyright : Copyright (c) 2014-2016 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs = libbutl%lib{butl}

exe{driver}: cxx{driver} $libs test{cleanup redirect status}

include ../../../../../build2/
