# file      : unit-tests/cc/lexer/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

#@@ Temporary until we get utility library support.
#
import libs = libbutl%lib{butl}
src = cc/lexer token lexer diagnostics utility variable name b-options     \
types-parsers context scope parser target operation rule prerequisite file \
module function functions-builtin functions-filesystem functions-path      \
functions-process-path functions-regex functions-string                    \
functions-target-triplet algorithm search dump filesystem scheduler        \
config/{utility init operation module} spec

exe{driver}: cxx{*} ../../../build2/cxx{$src} ../../../build2/liba{b} \
             $libs test{*}

include ../../../build2/
