using cxx

lib{utility}: cxx{utility}
exe{driver}: cxx{driver} #lib{utility}

#exe{driver}: test.roundtrip = test.out

exe{*}: test = true
exe{*}: test.output = test.out

./: lib{utility} exe{driver}
#./: exe{driver}
