# file      : unit-tests/test/script/lexer/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

#@@ Temporary until we get utility library support.
#
import libs = libbutl%lib{butl}
src = token lexer diagnostics utility variable name b-options types-parsers \
test/script/{token lexer}

exe{driver}: cxx{driver} ../../../../build2/cxx{$src} $libs \
test{command-line first-token second-token command-expansion variable-line \
     description-line variable}

include ../../../../build2/
