# file      : tests/parser/buildfile
# copyright : Copyright (c) 2014-2019 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs = libbutl%lib{butl}

exe{driver}: cxx{driver ../../build/{token lexer parser scope target \
 prerequisite variable operation rule search algorithm file module dump \
 context diagnostics name path-io utility}} $libs
