#v = (:bar) # error: expected name instead of ':'
#v = (foo:) # error: scope/target expected after ':'

print (foo:bar)
print (foo :bar)
print (foo: bar)
print (foo : bar)
print (foo/: bar)
print (foo/file{fox}: bar)

bar=bar
sub/:
{
  bar=Bar
  fsdir{./}: bar=BAR
  file{x}: bar=BBAARR
}

print $(./:bar)
print $(sub/:bar)
print $(fsdir{sub/}:bar)
print $(sub/file{x}:bar)

print $(sub/file{y}:bar)
print $(sup/:bar)

./:
