using cli

lib{test}: cxx{utility} cli.cxx{test base} extra/cxx{test}
cli.cxx{test}: cli{test}
cli.cxx{base}: cli{base}

cli.options += -I $src_root --include-with-brackets

extra/:
{
  cxx{test} hxx{test}: cli{test}
  cli.options += --include-prefix test/extra --guard-prefix TEST_EXTRA \
    --cli-namespace test::extra::cli
}

cxx.poptions += -I$out_root -I$src_root
lib{test}: cxx.export.poptions = -I$out_root -I$src_root

cli.options += --include-prefix test --guard-prefix TEST \
--cli-namespace test::cli
